version: '3'
services:
  api:
    build: .
    ports:
      - "9052:8000"
    deploy:
      resources:
        limits:
          memory: 1000M

  rproxy:
    hostname: rproxy
    image: mattes/rotating-proxy:latest
    deploy:
      replicas: 2
    environment:
      - tors=25

  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db


networks:
  default:
    external:
      name: m11s

volumes:
  mongo-data: