version: '3'
services:
  api:
    build: .
    ports:
      - "9052:8000"
    deploy:
      resources:
        limits:
          memory: 1000M

  rproxy:
    hostname: rproxy
    image: mattes/rotating-proxy:latest
    deploy:
      replicas: 2
    environment:
      - tors=25

  mongodb:
    image: mongo:5
    volumes:
      - mongo-data:/data/db

  splash:
    image: scrapinghub/splash:3.5
    command: --max-timeout 130
    deploy:
      resources:
        limits:
          memory: 1000M

volumes:
  mongo-data:
